### PR TITLE
[MSHADE-378] Shade plugin changes the compression level of nested jar…

### PR DESCRIPTION
**Pull request by jenrryyou**
Shade plugin loses the meta information of orignal jar entries when copying nested jar, which make these nested jar can't be loaded by JVM。This PR is trying to fix it by modified the copy logic for JarEntry.

The jira ticket link: https://issues.apache.org/jira/projects/MSHADE/issues/MSHADE-378?filter=allopenissues

### CODE REVIEW

**Comment by rmannibucau** [comment]
Hi @jenrryyou ,

the PR looks good but is it possible to add a test about this case (thinking out loud DefaultShaderTest can be a base and required to generate a fake jar with nested jar using TemporaryFolder as base).

Impl side note: a PushbackInputStream can probably avoid a custom inputstream impl and still enable to test the zip header.

**Comment by jenrryyou** [comment]
Hi @rmannibucau ,
thanks for your review and comment，I will add a test for this case. As for using PushbackInputStream, it seems like a better 
idea and I will try it also.

**Comment by jenrryyou** [comment]
Hi @rmannibucau ,
A test is added for this PR to verify that shade plugin wouldn't change the compression level of nested jar.  By the way,  ZipHeaderPeekInputStream is refined and  based on PushbackInputStream now.

**Review by rmannibucau — APPROVED** [review]

**Comment by jenrryyou** [comment]
[MSHADE-378] Shade plugin changes the compression level of nested jar entries, see more at this [jira ticket link](https://issues.apache.org/jira/projects/MSHADE/issues/MSHADE-378?filter=allopenissues)

**Comment by jenrryyou** [comment]
Hi @rmannibucau ,
Since I have no write access for this repo，I was wondering if you could merge this PR or somebody else would do?

**Comment by jira-importer** [comment]
Resolve #684

**Comment by jira-importer** [comment]
Resolve #684

**Pull request merged**
