### PR TITLE
[MSHADE-316] Minijar Exemptions

### PR DESCRIPTION
**Pull request by mkarg**
Implements https://issues.apache.org/jira/browse/MSHADE-316.

New configuration option <exemptions> allows to specify patterns for files to be exempted from getting discarded by minijar filter.

### CODE REVIEW

**Comment by mkarg** [comment]
@rfscholte Review please. :-)

**Comment by mkarg** [comment]
Replaced by alternative solution #19 due to decision of @rfscholte .

**Comment by jira-importer** [comment]
Resolve #317

**Comment by jira-importer** [comment]
Resolve #317

**Pull request closed without merging**
