### PR TITLE
upgrade to asm 7.2

### PR DESCRIPTION
**Pull request by sullis**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MSHADE) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MSHADE-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MSHADE-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by Tibor17** [comment]
Here is the release notes [support for J13 and J14](https://asm.ow2.io/versions.html).
@rfscholte This version `7.2` should be set in https://github.com/codehaus-plexus/plexus-languages/blob/master/plexus-java/pom.xml#L70 as well and then we can release plugins which are dependent on `plexus-java`.

**Comment by eolivelli** [comment]
What is the better approach?
Wait for a plexus release or patch this plugin?
I see pros and cons in both of the two ways

**Comment by Tibor17** [comment]
@eolivelli Let's merge this fix and release this plugin. The Plexus Java is used in Surefire but it is Codehaus, not Maven gid.

**Comment by Tibor17** [comment]
@sullis pls create Jira ticket and rewrite the commit message, thx.

**Comment by rfscholte** [comment]
> Do you agree with updating plexus-java and cutting a new version 1.0.4?

ASM is a direct dependency of maven-shade plugin, so this PR is correct. No need to worry about plexus-java, the ASM code won't be used.

**Comment by Tibor17** [comment]
It's simple. I mentioned plexus-java because surefire is dependent on it and thus transitive dep ASM. So we have a common problem, updates due to new J13 and J14.

**Pull request merged**
