### PR TITLE
[MSHADE-318] - Include transitive dependencies

### PR DESCRIPTION
**Pull request by mkarg**
Fixes [MSHADE-318](https://issues.apache.org/jira/projects/MSHADE/issues/MSHADE-318) - Specifically included class's dependencies are missing.

Solution: Include transitive dependencies of specifically included classes.

- [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by mkarg** [comment]
I withhold this fix in the draft state until #19 is merged, as my solution builds ontop of that.

**Comment by mkarg** [comment]
@khmarbaise Review please. :-)

**Comment by mkarg** [comment]
@jvanzyl @olamy @brettporter Review please! :-) This issue is waiting for a review since one month. How are we supposed to work together if *all* my PRs are unprocessed for *weeks*?

**Comment by mkarg** [comment]
@struberg Review please. :-)

**Comment by mkarg** [comment]
@rfscholte @khmarbaise Ping ;-)

**Comment by jira-importer** [comment]
Resolve #322

**Comment by jira-importer** [comment]
Resolve #322

**Pull request merged**
