### PR TITLE
[MSHADE-311] - Don't add exclusions for provided dep

### PR DESCRIPTION
**Pull request by famod**
Since the Exclusion logic in `ShadeMojo.updateExcludesInDeps(MavenProject, List<Dependency>, List<Dependency>)` was introduced for `promoteTransitiveDependencies=true` (see https://github.com/apache/maven-shade-plugin/commit/13c6097fffaa85d1ea40752cef732d6548e43e2c and [MSHADE-31](https://issues.apache.org/jira/browse/MSHADE-31)) which doesn't affect `provided` dependencies anyway, a simple scope check was sufficient to fix this problem.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MSHADE) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MSHADE-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MSHADE-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by famod** [comment]
Btw: I find it very unfortunate that back then MSHADE-31 did _not_ introduce a test.
So my new integration test seems to be the first test actually testing the dependency reduced POM for the presence/absence of `exclusions` (but only for a very specific scenario).

In case `prodvided` scope dependencies are ever fully adressed by this plugin (which would make sense by the way, see also [MSHADE-89](http://jira.codehaus.org/browse/MSHADE-89) and [MSHADE-181](http://jira.codehaus.org/browse/MSHADE-181)), the entire `exclusions` handling should be re-implemented. The current approach might have been influenced by older Maven versions, but from a recent POV: Why isn't the Plugin just checking the original exclusions of the original pom? Instead is is (IMHO) trying to "guess" what _might_ have been an exclusion before all the shading.

**Comment by khmarbaise** [comment]
Let's see what our CI says https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-shade-plugin/job/famod-MSHADE-311-dep-red-pom-excludes/

**Comment by khmarbaise** [comment]
So CI is fine..will be merged into master. Thanks for your contribution.

**Comment by khmarbaise** [comment]
Has been merged into master.

**Comment by famod** [comment]
Thank you very much, @khmarbaise!

**Comment by jira-importer** [comment]
Resolve #312

**Pull request closed without merging**
