### PR TITLE
Update ASM to latest version

### PR DESCRIPTION
**Pull request by raphw**
Update to ASM 6.1.1

### CODE REVIEW

**Comment by struberg** [comment]
is probably related to MSHADE-275

**Comment by khmarbaise** [comment]
Exactly it is...

**Comment by raphw** [comment]
I did not know that but I just overruled the dependencies in my build within the <plugin> tag and I can now successfully build on Java 10. I had to do the same for the maven-plugin-plugin.

**Comment by khmarbaise** [comment]
Have you run the IT's ?

**Comment by raphw** [comment]
No, I meant that I can build my project on Java 10 that uses the Maven Shade plugin which did not build because of the outdated ASM version before.

**Comment by khmarbaise** [comment]
Ah very good. Misunderstanding on my site...that's good to know that it helps that way...Do you have a chance to test a SNAPSHOT version? I can offer one ....

**Comment by raphw** [comment]
Absolutely. It should even work if you fork the repository https://github.com/raphw/byte-buddy as CI picks up all branches.

**Comment by khmarbaise** [comment]
Ok created on and provided like this:
https://repository.apache.org/content/repositories/snapshots/org/apache/maven/plugins/maven-shade-plugin/3.1.1-SNAPSHOT/maven-shade-plugin-3.1.1-20180402.085120-121.jar

**Comment by raphw** [comment]
The snapshot works fine with my build.

**Comment by khmarbaise** [comment]
Great. So I can continue to make a new release of maven-shade-plugin. Thanks for your feedback.

**Comment by khmarbaise** [comment]
VOTE for new release of maven-shade-plugin 3.1.1 https://www.mail-archive.com/dev@maven.apache.org/msg116597.html has started.

**Comment by jira-importer** [comment]
Resolve #471

**Comment by jira-importer** [comment]
Resolve #471

**Pull request closed without merging**
