### PR TITLE
[MSHADE-306] log all duplicates to not silently swallow a duplicate and an implicit selection

### PR DESCRIPTION
**Pull request by rmannibucau**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MSHADE) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MSHADE-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MSHADE-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

- [X] already an ASF committer

### CODE REVIEW

**Comment by eolivelli** [comment]
@rmannibucau 
let's see CI
https://builds.apache.org/job/maven-box/job/maven-shade-plugin/job/MSHADE-306/

**Comment by rmannibucau** [comment]
seems i cant run the CI job but I hope my fixes solved the issue

**Comment by eolivelli** [comment]
@rmannibucau I will push the branch to master ASF repository so that CI will kick in.

I hope we will be able to let CI start automatically upon pull requests changes, but currently I think it is not possible because Maven CI is really complex and it is very tied to ASF repo.

as you know all Apache repos will be migrated to github and I hope it will be easier to change CI bindings.

**Comment by eolivelli** [comment]
@rmannibucau FYI
https://builds.apache.org/job/maven-box/job/maven-shade-plugin/job/MSHADE-306/3/

**Comment by pes2009j** [comment]
ipad

**Comment by khmarbaise** [comment]
Unfortunately there are Test failures: https://builds.apache.org/job/maven-box/job/maven-shade-plugin/job/MSHADE-306/

**Pull request merged**
